definitions:
  froms.CreatePostForm:
    properties:
      community_id:
        type: integer
      content:
        type: string
      title:
        type: string
    required:
    - community_id
    - content
    - title
    type: object
  froms.GetPostListStatusForm:
    properties:
      post_ids:
        items:
          type: integer
        type: array
    type: object
  froms.RegisterForm:
    properties:
      confirm_password:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - confirm_password
    - password
    - username
    type: object
  froms.UpdatePostForm:
    properties:
      content:
        type: string
      title:
        type: string
    required:
    - content
    - title
    type: object
  froms.VotePostForm:
    properties:
      direction:
        enum:
        - 1
        - 0
        - -1
        type: integer
      post_id:
        type: integer
    required:
    - post_id
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/community:
    get:
      consumes:
      - application/json
      description: 获取社区列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取社区列表
  /api/v1/community/{id}:
    get:
      consumes:
      - application/json
      description: 获取社区详情
      parameters:
      - description: 社区ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取社区详情
  /api/v1/post:
    get:
      consumes:
      - application/json
      description: 获取帖子列表
      parameters:
      - description: 页码
        in: query
        name: page
        required: true
        type: integer
      - description: 每页条数
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取帖子列表
    post:
      consumes:
      - application/json
      description: 创建帖子
      parameters:
      - description: 创建帖子表单
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/froms.CreatePostForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 创建帖子
  /api/v1/post/{id}:
    delete:
      consumes:
      - application/json
      description: 删除帖子
      parameters:
      - description: 帖子ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - ApiKeyAuth: []
      summary: 删除帖子
    get:
      consumes:
      - application/json
      description: 获取帖子详情
      parameters:
      - description: 帖子ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取帖子详情
    put:
      consumes:
      - application/json
      description: 更新帖子
      parameters:
      - description: 帖子ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新帖子表单
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/froms.UpdatePostForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 更新帖子
  /api/v1/post/{id}/vote:
    get:
      consumes:
      - application/json
      description: 获取用户投票
      parameters:
      - description: 帖子ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取用户投票
  /api/v1/post/status:
    get:
      consumes:
      - application/json
      description: 获取帖子列表状态
      parameters:
      - description: 帖子列表状态表单
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/froms.GetPostListStatusForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取帖子列表状态
  /api/v1/post/user/{id}:
    get:
      consumes:
      - application/json
      description: 获取用户帖子列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取用户帖子列表
  /api/v1/signup:
    post:
      consumes:
      - application/json
      description: 注册用户
      parameters:
      - description: 注册表单
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/froms.RegisterForm'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":1000,"msg":"success"}'
          schema:
            type: string
      summary: 注册
      tags:
      - user
  /api/v1/vote:
    post:
      consumes:
      - application/json
      description: 投票 for post
      parameters:
      - description: 投票表单
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/froms.VotePostForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 投票
swagger: "2.0"
